export const fundPerformanceData = [
  {
    id: 1,
    name: "Mogul Equities",
    ytd: "+12.8%",
    oneYear: "+15.3%",
    threeYear: "+11.2%",
    inception: "+14.7%",
    sharpe: 1.45,
    drawdown: "-8.1%",
  },
  {
    id: 2,
    name: "Mogul Digital Fund",
    ytd: "+48.2%",
    oneYear: "+62.4%",
    threeYear: "+78.9%",
    inception: "+92.3%",
    sharpe: 2.18,
    drawdown: "-22.4%",
  },
  {
    id: 3,
    name: "Mogul Real Estate",
    ytd: "+9.4%",
    oneYear: "+10.1%",
    threeYear: "+8.8%",
    inception: "+9.6%",
    sharpe: 1.62,
    drawdown: "-4.2%",
  },
  {
    id: 4,
    name: "Mogul Technologies",
    ytd: "+31.7%",
    oneYear: "+38.5%",
    threeYear: "+42.1%",
    inception: "+45.8%",
    sharpe: 1.89,
    drawdown: "-18.7%",
  },
  {
    id: 5,
    name: "Creative Arts Fund",
    ytd: "+22.1%",
    oneYear: "+25.6%",
    threeYear: "+20.3%",
    inception: "+23.9%",
    sharpe: 1.71,
    drawdown: "-12.5%",
  },
  {
    id: 6,
    name: "Mogul Recycling Fund",
    ytd: "+15.6%",
    oneYear: "+17.2%",
    threeYear: "+14.8%",
    inception: "+16.1%",
    sharpe: 1.58,
    drawdown: "-7.9%",
  },
];
